# Generated by Django 5.2.8 on 2025-11-27 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asunto', models.CharField(max_length=255)),
                ('fecha_evento', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuarios_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_foto', models.URLField(blank=True, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_creados', to=settings.AUTH_USER_MODEL)),
                ('expedientes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='movilizaciones.expedientes')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'registro',
            },
        ),
        migrations.CreateModel(
            name='HashTag_Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_catalogo_hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_registros', to='catalogos.catalogohashtag')),
                ('id_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_registros', to='movilizaciones.registro')),
            ],
            options={
                'verbose_name': 'Hashtag Registro',
                'verbose_name_plural': 'Hashtag Registros',
                'db_table': 'hashtag_registro',
                'unique_together': {('id_catalogo_hashtag', 'id_registro')},
            },
        ),
    ]
