# Generated by Django 5.2.8 on 2025-12-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movilizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientes',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
