# Generated by Django 5.2.8 on 2025-12-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilizaciones', '0002_expedientes_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expedientes',
            name='descripcion',
        ),
    ]
